version: 0.2
phases:
  install:
    commands:
      - echo Installing Docker Compose...
      - sudo curl -L --no-progress-meter --output /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64
      - sudo chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 782546527822.dkr.ecr.us-east-1.amazonaws.com
      - echo Login completed on `date`
  build:
    commands:
      - echo Build started on `date`
      # Build the Docker images
      - echo Building the production Docker image...
      - docker-compose --version
      - docker-compose --file=docker-compose-cloud.yml up --build -d
      - echo Build completed on `date`
  post_build:
    commands:
      # Take these images and push them to ECR
      - echo Pushing the Docker images...
      - docker tag src_landing-ui:latest 782546527822.dkr.ecr.us-east-2.amazonaws.com/hablaqui-staging-landing
      - docker tag src_api-restful:latest 782546527822.dkr.ecr.us-east-2.amazonaws.com/hablaqui-staging-api
      - docker push 782546527822.dkr.ecr.us-east-2.amazonaws.com/hablaqui-staging-landing
      - docker push 782546527822.dkr.ecr.us-east-2.amazonaws.com/hablaqui-staging-api
      - echo Pushing completed on `date`
      