steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
    dir: "landing"
    id: "install-landing"
    waitFor: ["-"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "FRONTEND_URL=${_FRONTEND_URL}"
      - "VUE_APP_URL=${_VUE_APP_URL}"
      - "VUE_APP_LANDING=${_VUE_APP_LANDING}"
    dir: "landing"
    id: "envvars-landing"
    waitFor: ["install-landing"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "generate"]
    dir: "landing"
    id: "generate-landing"
    waitFor: ["envvars-landing", "install-landing"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=landing"]
    dir: "landing"
    id: "deploy-landing"
    waitFor: ["envvars-landing", "install-landing", "generate-landing"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
    dir: "front"
    id: "install-front"
    waitFor: ["-"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "FRONTEND_URL=${_FRONTEND_URL}"
      - "VUE_APP_URL=${_VUE_APP_URL}"
      - "VUE_APP_LANDING=${_VUE_APP_LANDING}"
    dir: "front"
    id: "envvars-front"
    waitFor: ["install-front"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build"]
    dir: "front"
    id: "build-front"
    waitFor: ["envvars-front", "install-front"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "--version=$BRANCH_NAME",
        "--no-promote",
        "--no-stop-previous-version",
      ]
    dir: "front"
    id: "deploy-front"
    waitFor: ["envvars-front", "install-front", "build-front"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
    dir: "api"
    id: "install-api"
    waitFor: ["-"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "FRONTEND_URL=${_FRONTEND_URL}"
      - "VUE_APP_URL=${_VUE_APP_URL}"
      - "VUE_APP_LANDING=${_VUE_APP_LANDING}"
    dir: "api"
    id: "envvars-api"
    waitFor: ["install-api"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "--version=$BRANCH_NAME",
        "--no-promote",
        "--no-stop-previous-version",
      ]
    dir: "api"
    waitFor: ["envvars-api", "install-api"]

timeout: "2600s"
