version: "3.8"
# Se especifican los servicios que se van a ejecutar        
services:
  landing-ui:
    build:
      context: ./landing
      dockerfile: Dockerfile.cloud
      network: "host"
      args:
        - VUE_APP_URL
        - VUE_APP_LANDING
        - API_ABSOLUTE
    ports:
      - "9000:9000"
    container_name: vue-ui
    environment:
      - VUE_APP_LANDING=$VUE_APP_URL
      - VUE_APP_URL=$VUE_APP_URL
      - API_ABSOLUTE=$API_ABSOLUTE
  api-restful:
   # Se especifica el dockerfile que se va a utilizar
    build:
      context: ./api
      dockerfile: Dockerfile.cloud
    ports:
      - "3000:3000"
    container_name: node-api
    environment:
      - API_URL=$API_URL
      - MERCADOPAGO_KEY=$MERCADOPAGO_KEY
      - PORT=$PORT
      - SEGMENT_API_KEY=$SEGMENT_API_KEY
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - URLDB=$URLDB
      - VUE_APP_LANDING=$VUE_APP_LANDING