version: "3.9"
services:
  nodejs-server:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-api
    volumes:
      - ./api:/home/node/app
      - /home/node/app/node_modules
  vue-ui:
    build:
      context: ./landing
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    container_name: vue-ui
    volumes:
      - ./landing:/home/node/app
      - /home/node/app/node_modules
