version: "3.8"
# Se especifican los servicios que se van a ejecutar
services:
  api-restful:
   # Se especifica el dockerfile que se va a utilizar
    build:
      context: ./api
      dockerfile: Dockerfile.cloud
    ports:
      - "3000:3000"
    container_name: node-api
    environment:
      - URLDB=${_URLDB}
      - NODE_ENV=${_NODE_ENV}
      - PORT=${_PORT}
      - FRONTEND_URL=${_FRONTEND_URL}
      - JWT_SECRET=${_JWT_SECRET}
      - JWT_ALGORITHM=${_JWT_ALGORITHM}
      - JWT_EXPIRATION=${_JWT_EXPIRATION}
      - JWT_EXPIRATION_REFRESH=${_JWT_EXPIRATION_REFRESH}
      - JWT_SECRET_REFRESH=${_JWT_SECRET_REFRESH}
      - PASSWORD_RECOVERY_JWT_EXPIRATION=${_PASSWORD_RECOVERY_JWT_EXPIRATION}
      - API_URL=${_API_URL}
      - BUCKETNAME=${_BUCKETNAME}
      - MERCADOPAGO_KEY=${_MERCADOPAGO_KEY}
      - NO_REPLY_EMAIL=${_NO_REPLY_EMAIL}
      - NO_REPLY_PASSWORD=${_NO_REPLY_PASSWORD}
      - SEGMENT_API_KEY=${_SEGMENT_API_KEY}
      - SENDGRID_API_KEY=${_SENDGRID_API_KEY}
      - VUE_APP_LANDING=${_VUE_APP_LANDING}
      - KEY_API_TESTMAILS=${_KEY_API_TESTMAILS}
      - NAMESPACE_TESTMAILS=${_NAMESPACE_TESTMAILS}
  landing-ui:
    depends_on:
      - api-restful
    build:
      context: ./landing
      dockerfile: Dockerfile.cloud
    ports:
      - "9000:9000"
      - "8080:8080"
    container_name: vue-ui
    environment:
      - API_ABSOLUTE=http://api-restful:3000
      - FRONTEND_URL=${_FRONTEND_URL}
      - VUE_APP_URL=http://api-restful:3000/api/v1
      - HOST=0.0.0.0
      - PORT=8080