version: "3.8"
# Se especifican los servicios que se van a ejecutar        
services:
  landing-ui:
    build:
      context: ./landing
      dockerfile: Dockerfile.cloud
      network: "host"
      args:
        - VUE_APP_URL
        - VUE_APP_LANDING
        - API_ABSOLUTE
    ports:
      - "9000:9000"
    container_name: vue-ui
    environment:
      - VUE_APP_LANDING=$VUE_APP_URL
      - VUE_APP_URL=$VUE_APP_URL
      - API_ABSOLUTE=$API_ABSOLUTE
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.10
  api-restful:
   # Se especifica el dockerfile que se va a utilizar
    build:
      context: ./api
      dockerfile: Dockerfile.cloud
    ports:
      - "3000:3000"
    container_name: node-api
    environment:
      - API_URL=$API_URL
      - MERCADOPAGO_KEY=$MERCADOPAGO_KEY
      - PORT=$PORT
      - SEGMENT_API_KEY=$SEGMENT_API_KEY
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - URLDB=$URLDB
      - VUE_APP_LANDING=$VUE_APP_LANDING
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.20
  # Toda esta sección es para levantar el wordpress
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=$WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.30
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.40
  
networks:
  hablaqui-network:
    ipam:
      config:
        - subnet: 192.168.81.0/24