version: "3.8"
# Se especifican los servicios que se van a ejecutar        
services:
  api-restful:
   # Se especifica el dockerfile que se va a utilizar
    build:
      context: ./api
      dockerfile: Dockerfile.cloud
    ports:
      - "3000:3000"
    container_name: node-api
    environment:
      - API_ABSOLUTE=http://hablaqui-stagingapi-env.eba-5wjm5bfz.us-east-2.elasticbeanstalk.com
      - API_URL=http://hablaqui-stagingapi-env.eba-5wjm5bfz.us-east-2.elasticbeanstalk.com/
      - BUCKETNAME=hablaqui-content
      - DEBUG_ANALYTICS=true
      - FRONTEND_URL=http://hablaqui-staginglanding-env.eba-weneati6.us-east-2.elasticbeanstalk.com/#
      - GOOGLE_CLIENT_ID=1086967845709-nli3fg4d8nsjq34kk96j609ac57q3f2i.apps.googleusercontent.com
      - GOOGLE_CLIENT_REDIRECT=http://localhost:8080/google-calendar/success
      - GOOGLE_CLIENT_SECRET=Jw1CJ__C-XKfJnmnf7GuVBrn
      - JWT_SECRET=hablaqui2021
      - KEY_API_TESTMAILS=b70d3654-615f-4cf2-82b4-b0728c150646
      - MERCADOPAGO_KEY=TEST-6216809522314002-121800-d3f74fc45c5b7866a4a5072338f358eb-689750603
      - NAMESPACE_TESTMAILS=bnwxe
      - NODE_ENV=production
      - PORT=3000
      - SEGMENT_API_KEY=AH7mDfjeF72C2T0wnKcrZUO3S9YR4irK
      - SENDGRID_API_KEY=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
      - URLDB=mongodb+srv://hablaquistaging:oMOidIoeoTODtMHz@staging.qxxhuqm.mongodb.net/hablaqui
      - VUE_APP_LANDING=http://hablaqui-staginglanding-env.eba-weneati6.us-east-2.elasticbeanstalk.com/
      - VUE_APP_URL=http://hablaqui-stagingapi-env.eba-5wjm5bfz.us-east-2.elasticbeanstalk.com/api/v1
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.20
  landing-ui:
    build:
      context: ./landing
      dockerfile: Dockerfile.cloud
      network: "host"
      args:
        - API_BUILD=http://api-restful:3000
    ports:
      - "9000:9000"
      - "8080:8080"
    container_name: vue-ui
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - API_BUILD=http://api-restful:3000
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.10

networks:
  hablaqui-network:
    ipam:
      config:
        - subnet: 192.168.81.0/24