version: "3.8"
# Se especifican los servicios que se van a ejecutar        
services:
  api-restful:
   # Se especifica el dockerfile que se va a utilizar
    build:
      context: ./api
      dockerfile: Dockerfile.cloud
    ports:
      - "3000:3000"
    container_name: node-api
    environment:
      - API_URL=$API_URL
      - MERCADOPAGO_KEY=$MERCADOPAGO_KEY
      - PORT=$PORT
      - SEGMENT_API_KEY=$SEGMENT_API_KEY
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
      - URLDB=$URLDB
      - VUE_APP_LANDING=$VUE_APP_LANDING
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.20
  landing-ui:
    build:
      context: ./landing
      dockerfile: Dockerfile.cloud
      network: "host"
      args:
        - API_ABSOLUTE_ORIGINAL=$API_ABSOLUTE
        - VUE_APP_URL_ORIGINAL=$VUE_APP_URL
        - VUE_APP_LANDING=$VUE_APP_LANDING
    ports:
      - "9000:9000"
    container_name: vue-ui
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.10

networks:
  hablaqui-network:
    ipam:
      config:
        - subnet: 192.168.81.0/24