version: "3.8"
# Se especifican los servicios que se van a ejecutar        
services:
  api-restful:
   # Se especifica el dockerfile que se va a utilizar
    build:
      context: ./api
      dockerfile: Dockerfile.cloud
    # Se especifica el puerto que se va a utilizar y el puerto que se va a exponer
    ports:
      - "3000:3000"
    container_name: node-api
    # Se le da una dirección IP a los contenedores para que desde el front puedan acceder al back
    # durante la construcción (nuxt.config utiliza el back durante la construcción)
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.20
  landing-ui:
    build:
      context: ./landing
      dockerfile: Dockerfile.cloud
      # Se especifica "host" para que el contenedor pueda acceder a la red local
      network: "host"
    ports:
      - "9000:9000"
      - "8080:8080"
    container_name: vue-ui
    networks:
      hablaqui-network:
        ipv4_address: 192.168.81.10

networks:
  hablaqui-network:
    ipam:
      config:
        - subnet: 192.168.81.0/24