version: "3.8"
# Se especifican los servicios que se van a ejecutar
networks:
  custom_network:
    # Ip's estáticas para los contenedores
    ipam:
      driver: default
      config:
        - subnet: 192.168.81.0/24
        
services:
  landing-ui:
    depends_on:
      - api-restful
    build:
      context: ./landing
      dockerfile: Dockerfile.cloud
      network: custom_network
      args:
        - API_BUILD=http://api-restful:3000
    ports:
      - "9000:9000"
      - "8080:8080"
    container_name: vue-ui
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - API_BUILD=http://api-restful:3000
    networks:
      custom_network:
        ipv4_address: 192.168.81.10

  api-restful:
   # Se especifica el dockerfile que se va a utilizar
    build:
      context: ./api
      dockerfile: Dockerfile.cloud
      network: custom_network
    ports:
      - "3000:3000"
    container_name: node-api
    environment:
      - API_ABSOLUTE=http://hablaqui-staging.us-east-1.elasticbeanstalk.com
      - API_URL=http://hablaquistagingapi-env.eba-9ipn8u5m.us-east-2.elasticbeanstalk.com/
      - BUCKETNAME=hablaqui-content
      - DEBUG_ANALYTICS=true
      - FRONTEND_URL=http://hablaquistaginglanding-env.eba-xt3vgmpt.us-east-2.elasticbeanstalk.com/#
      - GOOGLE_CLIENT_ID=1086967845709-nli3fg4d8nsjq34kk96j609ac57q3f2i.apps.googleusercontent.com
      - GOOGLE_CLIENT_REDIRECT=http://localhost:8080/google-calendar/success
      - GOOGLE_CLIENT_SECRET=Jw1CJ__C-XKfJnmnf7GuVBrn
      - JWT_SECRET=hablaqui2021
      - KEY_API_TESTMAILS=b70d3654-615f-4cf2-82b4-b0728c150646
      - MERCADOPAGO_KEY=TEST-6216809522314002-121800-d3f74fc45c5b7866a4a5072338f358eb-689750603
      - NAMESPACE_TESTMAILS=bnwxe
      - NODE_ENV=production
      - PORT=3000
      - SEGMENT_API_KEY=AH7mDfjeF72C2T0wnKcrZUO3S9YR4irK
      - SENDGRID_API_KEY=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
      - URLDB=mongodb+srv://hablaquistaging:oMOidIoeoTODtMHz@staging.qxxhuqm.mongodb.net/hablaqui
      - VUE_APP_LANDING=http://hablaquistaginglanding-env.eba-xt3vgmpt.us-east-2.elasticbeanstalk.com/
      - VUE_APP_URL=http://hablaquistagingapi-env.eba-9ipn8u5m.us-east-2.elasticbeanstalk.com/api/v1
      # - URLDB=${_URLDB}
      # - BUCKETNAME=${_BUCKETNAME}
      # - GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}
      # - GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}
      # - NODE_ENV=${_NODE_ENV}
      # - PORT=${_PORT}
      # - FRONTEND_URL=${_FRONTEND_URL}
      # - JWT_SECRET=${_JWT_SECRET}
      # - JWT_ALGORITHM=${_JWT_ALGORITHM}
      # - JWT_EXPIRATION=${_JWT_EXPIRATION}
      # - JWT_EXPIRATION_REFRESH=${_JWT_EXPIRATION_REFRESH}
      # - JWT_SECRET_REFRESH=${_JWT_SECRET_REFRESH}
      # - PASSWORD_RECOVERY_JWT_EXPIRATION=${_PASSWORD_RECOVERY_JWT_EXPIRATION}
      # - API_URL=${_API_URL}
      # - BUCKETNAME=${_BUCKETNAME}
      # - MERCADOPAGO_KEY=${_MERCADOPAGO_KEY}
      # - NO_REPLY_EMAIL=${_NO_REPLY_EMAIL}
      # - NO_REPLY_PASSWORD=${_NO_REPLY_PASSWORD}
      # - SEGMENT_API_KEY=${_SEGMENT_API_KEY}
      # - SENDGRID_API_KEY=${_SENDGRID_API_KEY}
      # - VUE_APP_LANDING=${_VUE_APP_LANDING}
      # - KEY_API_TESTMAILS=${_KEY_API_TESTMAILS}
      # - NAMESPACE_TESTMAILS=${_NAMESPACE_TESTMAILS}
    networks:
      custom_network:
        ipv4_address: 192.168.81.20
  