steps:
  - name: node:12.10.0
    entrypoint: npm
    args: ["install"]
    dir: "landing"
    id: "install-landing"
    waitFor: ["-"]
  - name: node:12.10.0
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "FRONTEND_URL=${_FRONTEND_URL}"
      - "API_ABSOLUTE=${_API_ABSOLUTE}"
      - "VUE_APP_URL=${_VUE_APP_URL}"
      - "VUE_APP_LANDING=${_VUE_APP_LANDING}"
      - "MERCADOPAGO_KEY=${_MERCADOPAGO_KEY}"
      - "PUSHER_APP_ID=${_PUSHER_APP_ID}"
      - "PUSHER_SECRET=${_PUSHER_SECRET}"
      - "PUSHER_KEY=${_PUSHER_KEY}"
      - "PUSHER_CLUSTER=${_PUSHER_CLUSTER}"
      - "VUE_APP_PUSHER_BEAMS_INSTANCE=${_VUE_APP_PUSHER_BEAMS_INSTANCE}"
      - "VUE_APP_PUSHER_KEY=${_VUE_APP_PUSHER_KEY}"
      - "VUE_APP_PUSHER_CLUSTER=${_VUE_APP_PUSHER_CLUSTER}"
    dir: "landing"
    id: "envvars-landing"
    waitFor: ["install-landing"]
  - name: node:12.10.0
    entrypoint: npm
    args: ["run", "generate"]
    dir: "landing"
    id: "generate-landing"
    waitFor: ["envvars-landing", "install-landing"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "landing"
    id: "deploy-landing"
    waitFor: ["envvars-landing", "install-landing", "generate-landing"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
    dir: "front"
    id: "install-front"
    waitFor: ["-"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "FRONTEND_URL=${_FRONTEND_URL}"
      - "VUE_APP_URL=${_VUE_APP_URL}"
      - "VUE_APP_LANDING=${_VUE_APP_LANDING}"
      - "MERCADOPAGO_KEY=${_MERCADOPAGO_KEY}"
      - "PUSHER_APP_ID=${_PUSHER_APP_ID}"
      - "PUSHER_SECRET=${_PUSHER_SECRET}"
      - "PUSHER_KEY=${_PUSHER_KEY}"
      - "PUSHER_CLUSTER=${_PUSHER_CLUSTER}"
      - "VUE_APP_PUSHER_BEAMS_INSTANCE=${_VUE_APP_PUSHER_BEAMS_INSTANCE}"
      - "VUE_APP_PUSHER_KEY=${_VUE_APP_PUSHER_KEY}"
      - "VUE_APP_PUSHER_CLUSTER=${_VUE_APP_PUSHER_CLUSTER}"
    dir: "front"
    id: "envvars-front"
    waitFor: ["install-front"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build"]
    dir: "front"
    id: "build-front"
    waitFor: ["envvars-front", "install-front"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "front"
    id: "deploy-front"
    waitFor: ["envvars-front", "install-front", "build-front"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
    dir: "api"
    id: "install-api"
    waitFor: ["-"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "FRONTEND_URL=${_FRONTEND_URL}"
      - "LANDING_URL=${_LANDING_URL}"
      - "VUE_APP_URL=${_VUE_APP_URL}"
      - "VUE_APP_LANDING=${_VUE_APP_LANDING}"
      - "MERCADOPAGO_KEY=${_MERCADOPAGO_KEY}"
      - "PUSHER_APP_ID=${_PUSHER_APP_ID}"
      - "PUSHER_SECRET=${_PUSHER_SECRET}"
      - "PUSHER_KEY=${_PUSHER_KEY}"
      - "PUSHER_CLUSTER=${_PUSHER_CLUSTER}"
      - "VUE_APP_PUSHER_BEAMS_INSTANCE=${_VUE_APP_PUSHER_BEAMS_INSTANCE}"
      - "VUE_APP_PUSHER_KEY=${_VUE_APP_PUSHER_KEY}"
      - "VUE_APP_PUSHER_CLUSTER=${_VUE_APP_PUSHER_CLUSTER}"
      - "NO_REPLY_EMAIL=${_NO_REPLY_EMAIL}"
      - "NO_REPLY_PASSWORD=${_NO_REPLY_PASSWORD}"
      - "GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}"
      - "GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET}"
      - "GOOGLE_CLIENT_REDIRECT=${_GOOGLE_CLIENT_REDIRECT}"
    dir: "api"
    id: "envvars-api"
    waitFor: ["install-api"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "api"
    waitFor: ["envvars-api", "install-api"]

timeout: "2600s"
