# Google Cloud App Engine Configuration
# This file defines the deployment configuration for the Hablaqui landing page

# Runtime environment configuration
runtime: nodejs18  # Node.js 18 runtime environment
env: standard     # Standard App Engine environment

# Instance configuration
instance_class: F1  # F1 instance class (1 shared vCPU, 256MB memory)

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1    # Minimum number of instances
  max_instances: 10   # Maximum number of instances
  target_cpu_utilization: 0.65  # Target CPU utilization for scaling

# Environment variables
env_variables:
  NODE_ENV: "production"  # Set Node.js environment to production
  NUXT_HOST: "0.0.0.0"    # Host to bind the Nuxt.js server
  NUXT_PORT: "8080"       # Port to run the Nuxt.js server

# URL handlers
handlers:
  # Serve static files
  - url: /(.*\.(gif|png|jpg|ico|txt|json|js|css|woff|woff2|ttf|eot|svg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt|json|js|css|woff|woff2|ttf|eot|svg)$
    secure: always

  # Serve all other requests with the main application
  - url: /.*
    script: auto
    secure: always

# Security headers
security_headers:
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-XSS-Protection: 1; mode=block
  Strict-Transport-Security: max-age=31536000; includeSubDomains
