# Google App Engine configuration for Hablaquí Landing Page
# This file defines the deployment settings for the application

# Runtime environment configuration
runtime: nodejs14  # Node.js version 14 runtime
instance_class: F1  # Instance class for the application

# Automatic scaling configuration
automatic_scaling:
    max_instances: 3  # Maximum number of instances to scale to

# URL handlers configuration
handlers:
    # Serve Nuxt.js static files
    - url: /_nuxt
      static_dir: .nuxt/dist/client
      secure: always  # Enforce HTTPS

    # Serve static assets (images, icons, text files)
    - url: /(.*\.(gif|png|jpg|ico|txt))$
      static_files: static/\1
      upload: static/.*\.(gif|png|jpg|ico|txt)$
      secure: always  # Enforce HTTPS

    # Catch-all handler for all other routes
    - url: /.*
      script: auto  # Automatically detect the script to run
      secure: always  # Enforce HTTPS

# Environment variables
env_variables:
    HOST: '0.0.0.0'  # Host address for the application
