runtime: nodejs10
service: frontend
handlers:
    # Serve all static files withdd urls ending with a file extension
    - url: /(.*\..+)$
      static_files: dist/\1
      upload: dist/(.*\..+)$
      http_headers:
          Access-Control-Allow-Origin: '*'
    - url: /.*
      static_files: dist/index.html
      upload: dist/index.html
      http_headers:
          Access-Control-Allow-Origin: '*'
automatic_scaling:
    max_instances: 5
