# Hablaquí Mobile Application
# 
# This is the Flutter project configuration file for the Hablaquí mobile application.
# It defines the project metadata, dependencies, and asset configurations.

name: movil
description: Hablaquí mobile application for online therapy and specialist consultations.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version information
# Format: version_name+version_code
# - version_name: Semantic version (MAJOR.MINOR.PATCH)
# - version_code: Build number for app stores
# 
# Android: version_name = versionName, version_code = versionCode
# iOS: version_name = CFBundleShortVersionString, version_code = CFBundleVersion
version: 1.0.0+1

# SDK constraints
environment:
  sdk: ">=2.7.0 <3.0.0"

# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2  # iOS-style icons
  carousel_slider: ^3.0.0  # Image carousel widget
  font_awesome_flutter: ^9.1.0  # Font Awesome icons

  # Networking and Data
  http: ^0.13.3  # HTTP client for API requests
  shared_preferences: ^2.0.6  # Local storage
  flutter_pusher: ^1.0.2  # Real-time updates
  intl: ^0.17.0  # Internationalization and formatting

  # Platform Integration
  url_launcher: ^6.0.9  # URL handling and external links

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

# Flutter-specific configuration
flutter:
  # Enable Material Design
  uses-material-design: true

  # Asset configuration
  assets:
    - images/  # Application images and icons

  # Font configuration (commented out - add when needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
