# Flutter Project Configuration
# This file defines the configuration and dependencies for the Hablaqui mobile app

# Project metadata
name: hablaqui
description: Hablaqui - Mental Health Marketplace and SaaS Platform Mobile App
publish_to: 'none'
version: 1.0.0+1

# Environment configuration
environment:
  sdk: ">=2.17.0 <3.0.0"  # Dart SDK version constraints

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  # State management
  provider: ^6.0.5        # State management solution
  flutter_bloc: ^8.1.3    # BLoC pattern implementation
  
  # UI components
  cupertino_icons: ^1.0.5  # iOS-style icons
  flutter_svg: ^2.0.5     # SVG rendering
  cached_network_image: ^3.2.3  # Image caching
  
  # Networking
  dio: ^5.1.1            # HTTP client
  connectivity_plus: ^4.0.1  # Network connectivity
  
  # Storage
  shared_preferences: ^2.1.1  # Local storage
  hive: ^2.2.3           # NoSQL database
  hive_flutter: ^1.1.0   # Flutter integration for Hive
  
  # Authentication
  firebase_auth: ^4.6.2  # Firebase authentication
  google_sign_in: ^6.1.4  # Google Sign-In
  
  # Utilities
  intl: ^0.18.0         # Internationalization
  url_launcher: ^6.1.11  # URL handling
  package_info_plus: ^4.0.2  # App package information
  device_info_plus: ^9.0.2  # Device information

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2  # Flutter linting rules
  build_runner: ^2.4.4   # Code generation
  hive_generator: ^2.0.0  # Hive code generation

# Flutter configuration
flutter:
  # Material Design icons
  uses-material-design: true
  
  # Asset configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  
  # Font configuration
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300

# Flutter-specific configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    icon_background_color: "#FFFFFF"
  ios: true
  web: false
