runtime: nodejs10
instance_class: F1
automatic_scaling:
    target_cpu_utilization: 0.8
    max_instances: 3
    min_instances: 1
    idle_timeout: 59m

service: api
handlers:
    - url: /.*
      script: auto
