# Google Cloud App Engine Configuration for Hablaqui API
# This file defines the deployment configuration for the API service

# Runtime environment configuration
runtime: nodejs18  # Node.js runtime version
env: standard      # Standard environment for better performance

# Instance configuration
instance_class: F1  # Instance class (F1 is the smallest, suitable for development)

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1      # Minimum number of instances
  max_instances: 10     # Maximum number of instances
  min_idle_instances: 1 # Minimum idle instances
  max_idle_instances: 2 # Maximum idle instances
  min_pending_latency: 30ms  # Minimum latency before scaling
  max_pending_latency: 200ms # Maximum latency before scaling
  max_concurrent_requests: 50 # Maximum concurrent requests per instance

# Environment variables
env_variables:
  NODE_ENV: "production"
  PORT: "8080"

# URL handlers
handlers:
  # Serve static files
  - url: /static
    static_dir: static
    secure: always

  # Serve the main application
  - url: /.*
    script: auto
    secure: always

# Security headers
security_headers:
  # Enable HSTS
  - name: Strict-Transport-Security
    value: max-age=31536000; includeSubDomains
  # Prevent clickjacking
  - name: X-Frame-Options
    value: DENY
  # Enable XSS protection
  - name: X-XSS-Protection
    value: 1; mode=block
  # Prevent MIME type sniffing
  - name: X-Content-Type-Options
    value: nosniff
  # Content Security Policy
  - name: Content-Security-Policy
    value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
